<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ListaChequeoTrenMitico extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'hora_Inicio',
        'chequeo_Uno_Tren_Mitico',
        'chequeo_Dos_Tren_Mitico',
        'chequeo_Tres_Tren_Mitico',
        'chequeo_Cuatro_Tren_Mitico',
        'chequeo_Cinco_Tren_Mitico',
        'chequeo_Seis_Tren_Mitico',
        'chequeo_Siete_Tren_Mitico',
        'chequeo_Ocho_Tren_Mitico',
        'chequeo_Nueve_Tren_Mitico',
        'chequeo_Diez_Tren_Mitico',
        'chequeo_Once_Tren_Mitico',
        'chequeo_Doce_Tren_Mitico',
        'chequeo_Trece_Tren_Mitico',
        'chequeo_Catorce_Tren_Mitico',
        'chequeo_Quince_Tren_Mitico',
        'chequeo_Dieciseis_Tren_Mitico',
        'chequeo_Diecisiete_Tren_Mitico',
        'chequeo_Dieciocho_Tren_Mitico',
        'chequeo_Diecinueve_Tren_Mitico',
        'chequeo_Veinte_Tren_Mitico',
        'chequeo_Ventiuno_Tren_Mitico',
        'chequeo_Ventidos_Tren_Mitico',
        'chequeo_Ventitres_Tren_Mitico',
        'chequeo_Venticuatro_Tren_Mitico',
        'chequeo_Venticinco_Tren_Mitico',
        'chequeo_Ventiseis_Tren_Mitico',
        'chequeo_Ventisiete_Tren_Mitico',
        'chequeo_Ventiocho_Tren_Mitico',
        'chequeo_Ventinueve_Tren_Mitico',
        'chequeo_Treinta_Tren_Mitico',
        'chequeo_Treintauno_Tren_Mitico',
        'chequeo_Treintados_Tren_Mitico',
        'chequeo_Treintatres_Tren_Mitico',
        'chequeo_Treintacuatro_Tren_Mitico',
        'chequeo_Treintacinco_Tren_Mitico',
        'chequeo_Treintaseis_Tren_Mitico',
        'chequeo_Treintasiete_Tren_Mitico',
        'chequeo_Treintaocho_Tren_Mitico',
        'chequeo_Treintanueve_Tren_Mitico',
        'chequeo_Cuarenta_Tren_Mitico',
        'chequeo_Cuarentauno_Tren_Mitico',
        'chequeo_Cuarentados_Tren_Mitico',
        'chequeo_Cuarentatres_Tren_Mitico',
        'chequeo_Cuarentacuatro_Tren_Mitico',
        'chequeo_Cuarentacinco_Tren_Mitico',
        'chequeo_Cuarentaseis_Tren_Mitico',
        'chequeo_Cuarentasiete_Tren_Mitico',
        'chequeo_Cuarentaocho_Tren_Mitico',
        'chequeo_Cuarentanueve_Tren_Mitico',
        'chequeo_Cincuenta_Tren_Mitico',
        'chequeo_Cincuentauno_Tren_Mitico',
        'chequeo_Cincuentados_Tren_Mitico',
        'chequeo_Cincuentatres_Tren_Mitico',
        'chequeo_Cincuentacuatro_Tren_Mitico',
        'chequeo_Cincuentacinco_Tren_Mitico',
        'chequeo_Cincuentaseis_Tren_Mitico',
        'chequeo_Cincuentasiete_Tren_Mitico',
        'chequeo_Cincuentaocho_Tren_Mitico',
        'chequeo_Cincuentanueve_Tren_Mitico',
        'chequeo_Sesenta_Tren_Mitico',
        'chequeo_Sesentauno_Tren_Mitico',
        'chequeo_Sesentados_Tren_Mitico',
        'chequeo_Sesentatres_Tren_Mitico',
        'chequeo_Sesentacuatro_Tren_Mitico',
        'chequeo_Sesentacinco_Tren_Mitico',
        'chequeo_Sesentaseis_Tren_Mitico',
        'chequeo_Sesentasiete_Tren_Mitico',
        'chequeo_Sesentaocho_Tren_Mitico',
        'chequeo_Sesentanueve_Tren_Mitico',
        'chequeo_Setenta_Tren_Mitico',
        'chequeo_Setentauno_Tren_Mitico',
        'chequeo_Setentados_Tren_Mitico',
        'chequeo_Setentatres_Tren_Mitico',
        'chequeo_Setentacuatro_Tren_Mitico',
        'chequeo_Setentacinco_Tren_Mitico',
        'chequeo_Setentaseis_Tren_Mitico',
        'chequeo_Setentasiete_Tren_Mitico',
        'chequeo_Setentaocho_Tren_Mitico',
        'chequeo_Setentanueve_Tren_Mitico',
        'chequeo_Ochenta_Tren_Mitico',
        'chequeo_Ochentauno_Tren_Mitico',
        'chequeo_Ochentados_Tren_Mitico',
        'chequeo_Ochentatres_Tren_Mitico',
        'chequeo_Ochentacuatro_Tren_Mitico',
        'chequeo_Ochentacinco_Tren_Mitico',
        'chequeo_Ochentaseis_Tren_Mitico',
        'chequeo_Ochentasiete_Tren_Mitico',
        'chequeo_Ochentaocho_Tren_Mitico',
        'chequeo_Ochentanueve_Tren_Mitico',
        'chequeo_Noventa_Tren_Mitico',
        'chequeo_Noventauno_Tren_Mitico',
        'observaciones',
        'hora_Fin',
        'imagen'
    ];

    public function user(){
        return $this->belongsTo(User::class);
    }
}
